apiVersion: v1
kind: ReplicationController
metadata:
  name: goapp-rc
spec:
  replicas: 5
  selector:
    app: goapp
  template:
    metadata:
      name: goapp-pod
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp-container
        image: dangtong/goapp
        ports:
        - containerPort: 8080