apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels:
    name: test2
    tier: FronEnd
    app: apache
spec:
  containers:
  - name: test2
    image: bitnami/apache
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
