---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - image: httpd:2.4.48-alpine
          name: httpd
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
