apiVersion: v1
kind: Pod
metadata:
  name: goapp-pod
  labels:
    name: goapp
    env: prod
spec:
  nodeSelector:
    memsize: "high"
  containers:
  - image: dangtong/goapp
    name: goapp-container-memhigh
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      protocol: TCP